title: ALESSANDRO ZANETTIN # name of the site
author: # name of site's author
email: zanettin.ale@gmail.com # email of site's author
url: https://sandrozanettin.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Currently an Economics & Business Student at University of Milano-Bicocca, Italy.
  <br>
  <br>email me at <a href="mailto:zanettin.ale@gmail.com">zanettin.ale@gmail.com</a>
  <br>Twitter <a href="https://twitter.com/sandrozanettin">@sandrozanettin</a>
  <br>LinkedIn <a href="https://www.linkedin.com/in/alezanettin/">/alezanettin</a>

permalink: # /:slug.html

favicon: # "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "..." # customize text for homepage link in post layout
  date_format: "%d-%m-%y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
